== How to use this book

Even though this book is mostly a compilation of several smaller ones, it is still designed to be read from top to bottom. The concepts and tools build on one another. The tasks associated with the tools, however, are designed to be re-learned often like an agent preparing for a special op. Повторение — мать учения. Repetition is the mother of learning. Anyone who has ever done anything in the military knows not all op procedures can be memorized and ready at all times, which is why you create your own little black book while reading this one, just like an _actual_ cybersecurity agent would in the field.

=== Don't just read it

Learning to hack from the terminal is going to take a lot more than this silly book. Don't misunderstand. You're gonna be doing a _lot_ of reading as a techie. Get used to it. But take some time now to figure out how you do more than just the stuff in this book. You can join a community, find a mentor, or become a mentor yourself. And speaking of mentoring, AI, heard of it? There's no better tool to assist you with learning this stuff, or learning _anything_ for that matter. Look into it.

=== Join a crew

We humans are social creatures. Learning is communal. Join a community that is focused on learning the same things as you. Meetups, hacker spaces, clubs, church groups, social media, and live streamer chat groups are all great places to find a community. The community is a place to collaborate and share peer reviews of one another's learning and projects. Who knows, you might find a friend. I did.

[NOTE]
====
My sincere hope is that the parents, teachers, and young hackers reading these words will find opportunities and motivation to create their own clubs and communities dedicated to helping others master the art of the terminal command line and bash scripting and all the well-earned benefits of doing so. While you are working on creating your own community, consider joining mine at https://linktr.ee/rwxrob.
====

=== Find a mentor

Humans have been passing knowledge one to another since the beginning. It's what we do. Wanna forge a sword or horse shoe? Better find the blacksmith and get them to show you their craft. Coding is no different. Just don't ask them to _teach_ you. They are probably too busy paying their bills doing what they are good at rather than spending that time teaching you how to do it. If you are respectful of their time, however, they might just be willing to mentor you—especially if you show genuine interest in their craft.

You will find that many people _want_ to share what they know but just don't know how to do it or who would want to hear. Find these people and approach them. Perhaps you can find a few mentors so you can compare how they differ in their approach to programming.

=== Become a mentor

Here's a secret a lot of people who get paid a lot of money don't want you to know, you don't need any special training to help someone else learn. In fact, as a beginner who has recently mastered something you are perhaps the best suited to help another beginner learn it because what made it click for you is still fresh in your mind. Ask a veteran when the last time anything clicked for them? They get so used to what they do they completely forget what it was like to be a beginner. So don't be shy. Offer your help to another beginner. And remember, you really haven't learned it until you can help someone else learn it as well.

include::trust-me-kiddo.adoc[]

include::say-hello-chloe.adoc[]
