== Be yourself

It's easy to say but really hard to do once you become a dancing monkey discovering what attracts people and gets them to throw treats at you. Some of the lessons learned are obvious, others not so much. Here's stuff I had to learn, personally:

- This isn't a job. This is my personal life.

- Authenticity takes a lot less effort to maintain. I've got far too many hours wasted appealing to other kachi-wearing business and church people in my life to waste another second on perception management—especially in my own free time.

- It's okay to be elite. I don't have to pretend to be a person who accommodates everyone just to keep them watching.

- It's okay to be an asshole. There's a scene in _Silicon Valley_ where Richard is berated for not being enough of an asshole. It's not like I aspire to be one, I already am. That's who I am and I'm done apologizing for it. Livestreaming means people see you.

- I found myself not wanting to stream because it interfered with stuff I wanted to work on and watching me do those things isn't "streamable content". I've never reached 75 average viewers and never will. My content is too long and boring and _real_ for that.

- People who like my content _really_ like my content. If you build it they will come. Some of the most amazing humans I have ever met have found me by putting myself out there. Had I pretended to be someone who doesn't appreciate what Perl is and why, or why bash matters, they might not have stayed and they certainly would still be influenced by other people who have quit their _actual_ jobs to pedal influence based on what sells and gets the most sponsors.
