== Install bash shell

The **bash shell** (short for Bourne Again Shell) is a versatile command-line interface available on most operating systems. It's ubiquitous, powerful, and easy to use. Don't worry too much about that that all means for now. We'll talk more about it later. Let's go get it.

=== Install Git-Bash on Windows

Windows doesn't come with bash so we'll install it. Git Bash provides a basic bash that plays nice with Windows and does everything we want.

Launch a `powershell` by tapping the `Win` key to pull up the search box and entering the word `powershell` then tapping `Enter`. You should see a terminal come up. Now type in the following and press `Enter`:

[source, shell]
----
winget install --id git.git
----

This installs bash at `"C:\Program Files\Git\bin\bash.exe"`.

Launch the new Git Bash terminal now by first closing your `powershell` window and then opening a new Git Bash one instead by tapping `Win` and typing `bash` into the search bar this time and tapping `Enter`. You getting the hang of it?

You should see a terminal come up, again, but this one looks different. You will probably want to increase the font size (`Control - +`) and stuff a bit but don't bother too much because we will be installing WezTerm later, a much better terminal program.

=== Update bash on macOS

Mac computers come with an outdated bash by default. You can update it using Homebrew (`brew`) but first we need to install the `brew` command using the built-in Terminal app.

[NOTE]
====
I really don't like how complicated it is to install `brew`. I never have. I wish there were something to download and install—especially for beginners. There simply isn't. Just know the stuff after this will actually not require a lot of complicated long commands that we just have to do without understanding them.
====

Launch the `terminal` program by pressing `Command + Space` and entering `terminal` into the Spotlight box. Then type the following:

[source, shell]
----
bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
----

Once brew is installed you can use it to update bash with the following command:

[source, shell]
----
brew install bash
----

Unfortunately, Apple makes it hard to set this new bash shell as the default. Here's how. Enter each of these commands one at a time:

[source, shell]
----
echo "$(brew --prefix)/bin/bash" | sudo tee -a /etc/shells
chsh -s "$(brew --prefix)/bin/bash"
----

After you install WezTerm it will use the new bash shell. For now just do `exec bash -l` to start using the new bash in the same terminal window.

[NOTE]
====
FunFact: Homebrew is named after the meetup where Steve Jobs and Steve Wozniak met for the first time before they created Apple Computer company.
====

=== Validate bash on Linux

Bash is pre-installed on most Linux distributions, as it is the default shell for many systems. All Linux distributions have a bash that is plenty new enough for everything we are going to do in this book.
