== Setup Go development

Setting up a Go development environment in the terminal is an essential ritual for any Code Mage aspiring to master this language of power. Installing and configuring Go is ridiculously easy:

[source, shell]
----
cd
cd dot
./install/go
----

You can look at the script (as usual) if you wish. There's nothing new in it at this point, same old `brew`, `winget`, and `apt` stuff.

[NOTE]
====
It's worth noting that this method of installation is easy, but doesn't always get us the latest and greatest `go` binary. Go handles updating itself pretty well, however, so this won't be a problem for this book.
====

=== Environment variables

They have already been set for you in `~/.bashrc` but it is worth knowing about them. I'm not going to explain the environment variables at all in this book since there are plenty of places you can read about them starting with https://github.com/rwxrob/awesome-go[_my awesome-go list_].

To list all the environment variables (we'll get into what a _variable_ even means to coders later):

[source, sh]
----
go env
----

[NOTE]
====
I only mention this because you might be talking about your Go development with another experienced Go developer and if you are having problems they will likely want to know this stuff.
====
