[[prepare]]
= Prepare to code

Learning happens in the lab, not the lecture hall. You can't make spells or swords without a lab or forge. So let's make one.

[NOTE]
====
In my Calculus 101 class in college I sat in a lecture hall filled with hundreds. None of us knew each other. I was still trying to figure out the whole college thing. I was good at math, but just couldn't figure some of this stuff out. I was _really_ struggling. I got so frustrated I mentioned it to a random stranger sitting next to me one day. He said, "have you tried the math lab?" I had not.

I immediately found it. I will never forget that feeling walking in for the first time, warmth from the Utah winter cold, my glasses fogging,  everyone having fun, focusing, learning, chatting, getting mentored by teacher's assistants with Ph.Ds in math flexing on the struggling pleebs—in a good way—helping them make calculus relatable. It was glorious. I learned so much in that lab. The learning there was messy and loud, but it was infectious and effective. And that's how I came by the saying: _learning happens in the lab, not the lecture hall._
====

Here's what we'll need:

- Bash command shell
- GitHub account
- Dotfiles configuration
- Wezterm terminal
- Neovim editor
- Go programming language
- Markdown for notes
- Git for saving and sharing

[CAUTION]
====
You don't need more than this. Avoid the temptation to customize everything for now. You'll have plenty of time to do that later.
====

include::bash.adoc[]

---

include::github.adoc[]

---

include::github-cli.adoc[]

---

include::github-login.adoc[]

---

include::dotfiles.adoc[]

---

include::bash-setup.adoc[]

---

include::wezterm.adoc[]

---

include::neovim.adoc[]

---

include::learn-vim.adoc[]

---

include::markdown.adoc[]

---

include::review-shell.adoc[]

---

include::golang.adoc[]
