== Install tmux multiplexer

Tmux is a powerful terminal multiplexer that allows you to manage multiple terminal sessions from a single interface, making it an essential tool for any Code Mage. With Tmux, you can split your terminal into multiple panes, run multiple programs simultaneously, and keep sessions running even after you disconnect—perfect for long-running processes or remote work. It’s like having a portal that keeps all your active spells organized and ready to cast at any time. Whether you’re coding, monitoring logs, or managing servers, Tmux enhances your efficiency by letting you switch between tasks seamlessly, customize layouts, and even script repetitive actions. For those who want to take their command-line wizardry to the next level, Tmux is an indispensable artifact.

=== Mac with brew

[source,shell]
----
brew install tmux
tmux -V
----

=== Windows does not have

Windows unfortunately does not have a version of tmux automatically prepared to work with Git Bash. Every way to get tmux installed is equally annoying and usually not worth the extra work when using an actual Linux machine in a podman container or virtual machine is better. Since technically you do not require tmux to code the stuff in this book, Windows users can hobble along without it. This is one of the many reasons developers prefer Mac and Linux machines (and the reason Microsoft has tried to convince the world to use its broken WSL Linux virtual machine, which you should <<why-not-wsl, absolutely not use>>).

=== Linux with apt

[source,shell]
----
sudo apt install tmux
tmux -V
----
