== Install Code-Mage with go

Code-Mage is contained in the `cm` command. See the <<cm-summary, summary>> in the Preface for more about what it does. Unlike everything most everything else we've installed so far, we are going to use the `go` command itself to install the `cm` command directly from compiled source. This is the best way to install any Go project. It is the safest since the entire code of the project can be read by anyone to ensure there has been no tampering (as opposed to downloading some executable off the Internet). Plus you always get the latest unless you specify another specific version.

After opening a terminal enter the following commands to install and then test it:

[source,shell]
----
GOPROXY=direct go install github.com/rwxrob/code-mage/cmd/cm@latest
cm help
----

This same command can be used any time to update to the latest version and works for installing any Go command as well. You will be doing it a lot to get the latest digital copy of this book and more.
