== Install Alacritty terminal

Alacritty is a modern, GPU-accelerated terminal emulator known for its speed and simplicity. It's speed and support for millions of colors make it particularly good for creating performant terminal animations and games, which always make fun micro-projects when learning the coding fundamentals. This guide walks you through installing official Alacritty on Mac, Windows, and Linux by using the package managers (discussed previously).

[NOTE]
====
Notice how similar these modern package managers are (`brew`, `winget`, `apt`). All operating systems have finally caught up to using a package manager for software installation and management. Becoming proficient with them is therefore mandatory for any serious tech professional.
====

=== Mac with brew

Run the following commands one at a time:

[source, shell]
----
brew install alacritty
alacritty --version
----

=== Windows with winget

Run the following commands one at a time:

[source, shell]
----
winget install --id alacritty.alacritty
alacritty --version
----

=== Linux with apt

Run the following commands one at a time:

[source, shell]
----
sudo add-apt-repository ppa:aslatter/ppa
sudo apt update
sudo apt install -y alacritty
alacritty --version
----

[CAUTION]
====
Don't worry about customization for now. Running `cm init` later will automatically configure the Alacritty teminal to startup up with a nice theme and font and reasonable defaults. You can always come back and update them in `~/.config/alacritty/alacritty.toml` file later.
====
