[[install-pde]]
== Install PDE

Every great mage has their sanctum, a personal development environment (PDE) where spells are honed and wonders are crafted—a carefully constructed digital workspace where ideas come to life, lines of code flow seamlessly, and creativity flourishes. Crafting a PDE is not merely about tools and configurations; it’s an act of self-discovery and empowerment. A terminal-based PDE will seem daunting at first, like learning to play a fine instrument, but the power and music it produces later will resonant far better than any GUI alternative. Terminal interfaces aren't just "for boomers" they are for a discrete, discerning set of technologists who operate on a magical plane much higher than most of their peers.

This section shows how to install all the components of your PDE with Code-Mage assistant—transforming your computer into a professional coder workstation with just one command—and then summarizes the components that were installed and configured for you so you can understand what happened. In fact, you can customize these later on your own. Everything that the Code-Mage assistant does is well explained in the <<behind-the-curtain, Behind the Curtain>> section at the end of the book.

=== Install rwxrob-books

[CAUTION]
====
You must have permission to install software onto your computer, both policy-wise and the actual administrative permissions to your computer. If this is a work or school computer be sure you have that permission before installing or running anything.

As to the security of `rwxrob-books` command and its installer, both are available for vetting and review on GitHub so that compiled binaries can be independently confirmed at any time to ensure I am not sneaking something onto your computer. Otherwise, I would not have passed preventing the installers from being added to the main registry.
====

Assuming you have don't know what a _package manager_ and have never heard of Linux before you can just go to the following URL, download the installer for your computer, and double-click it in your Downloads:

https://github.com/rwxrob/books/releases/latest

- `.msi` for Windows
- `.pkg` for macOS (`arm64` for newer macs)
- `tar.gz` for Linux (you know what to do)

If you _do_ have and know how to use a package manager, the following should also work:

- Windows: `winget --id rwxrob.books -e`
- macOS: `brew install rwxrob-books`

Those package manager steps can be repeated later to make sure you always have the latest.

=== Package manager: brew, winget

A reliable package manager is essential for managing dependencies, libraries, and tools effortlessly. On macOS, Homebrew (`brew`) reigns supreme, while Linux users can rely on apt (for all Linux distros supported in this book). Even Windows has embraced the modern winget package manager. You will soon see in the next steps that these tools significantly simplify installing and maintaining the components of your PDE, ensuring everything stays up-to-date and compatible.

=== Shell: bash

Learning bash equips beginners with practical skills that directly translate to real-world tasks, providing a strong base for exploring more advanced tools and programming languages. The bash shell is the official Linux shell and a cornerstone of command-line environments. Most modern shell scripts are written in bash, which is actually safer than its POSIX shell predecessors when written correctly (double brackets instead of single, for example). Windows doesn't come with bash so Git-Bash needs to be installed. Even though bash is preinstalled on Mac, it is very old and needs to be updated. All Linux systems come with the most recent bash so it need not be installed. Later, Code Mage assistant installs an initial `~/.bashrc` file that can be further customized later and saved to your "dot files" on GitHub.

=== Terminal: alacritty

[CAUTION]
====
You either get why the terminal user interface is superior or you don't. No one is going to fight with you about it. You do you. Just know that if you aren't willing to give the terminal a try then this book isn't for you. Stop reading now. When you eventually realize just how powerful the terminal can be this book will still be here waiting for you.
====

Speed matters when navigating your PDE. The default terminals that come on all operating systems are really pretty slow, some don't even implement the entire ANSI escape sequence set making them much less fun to use. So a GPU-accelerated terminal like Alacritty offers blazing-fast rendering, smooth scrolling, and a modern interface. This ensures that your terminal keeps up with your pace, allowing for a more seamless and efficient workflow. Plus, this makes creating fun terminal animations and games all the more entertaining and—more importantly—memorable so you remember what coding skill or principle you learned while making it.

[NOTE]
====
FunFact: The proper name for a _terminal_ is actually _terminal emulator_ since text terminals all originated from teletype machines. References to their origins still abound: terminals drivers are called `tty` devices, text lines all end with `\n` (line feed) and/or `\r` (carriage return), etc.
====

=== Theme: gruvbox-material

Don’t underestimate the power of aesthetics. A visually pleasing color scheme, like Gruvbox or Solarized, can make hours of coding feel less like a grind and more like art. Color syntax highlighting makes short work of understanding a complex bit of code. Code Mage assistant will install this theme in the next steps.

[NOTE]
====
I once found a critical error in a core configuration file managing all secure shell access to an enterprise computer. The mistake was trivial, but serious, had the person been using a color terminal instead of their beloved black and white putty they would have caught it instead of me.
====

=== Editor: n/vi/m + plugins

Your editor is the heart of your PDE. There's no beating the minimalist power of `vi` (pronounced "vee-eye") the visual extension of `ex`, a descendent of `ed` the first official Unix text editor. Vim and Neovim are its descendants.

**Vi is everywhere**: Sure you could learn a GUI editor like VSCode (your friends certainly are) but vi is on just about everything by default and is preferred by discerning technologists who want to be good on any Unix-like system they encounter (rather than only their own bloated workstation). Even if you prefer a GUI editor later, say for web development (which makes sense), it is still best to learn vi first.

**Vi navigation is in more than just editors**: Lots of things that have nothing to do with editing text files depend on "vim bindings." This includes every Unix-like shell ever made (activated with `set -o vi`).

**Vim filters**: The `vim` filter commands (`!!`,`!}`, etc.) provide powerful shell integration that most other editors just can't touch.

_Some may wish to read <<why-no-nano, Why no nano?>>_

[NOTE]
====
Now is a good time to mention the principle of _progressive enhancement_. You will likely hear about this again if you ever do any web development. The P in PWA stands for this principle which is that all applications should detect the minimum functionality available for use and progressively add on functionality as more advanced functionalities are detected. For example, a web app should work with just basic static web pages by default, but if JavaScript is detected it can upgrade itself and start using that. This way the most users are supported without unnecessarily blocking those that don't have the higher functionality. It's just good design.

A solid example of this that relates to your shiny new PDE is the `vi` alias which will use bare-bones `vi` if that is all that is available, or `vim` if detected, or `nvim` if detected. That way the same configuration (in this case `~/.bashrc` works no matter what on machine you put it on). This flexibility is crucial to discerning technologists who want to be quickly productive on _any_ system they might work on. (_See <<why-vimrc, Why ~/.vimrc?>> for more on this._)
====

[CAUTION]
====
As great as Neovim is, it can get just as slow and bloated as graphical editors when people get carried away, which has become something of a meme. Therefore, keep your vim setup clean and light for now.
====

=== Window manager: tmux

"What's your window manager?" That's a question people with way too much time on their hands will ask you. Soon you can answer "tmux!"

Strictly speaking tmux is a terminal session manager, a _multiplexer_ (i.e. multiple screens, like a movie ciniplex) not a _window manager_ according to most people's definition, which is normally associated with a graphic user interface even though `Ctrl-w` in tmux stands is for "terminal windows" so yeah, tmux _is_ a window manager.

Tmux isn't _just_ for managing windows, it also provides universal cut and paste functionality without leaving the terminal (stuff you cannot do with just a terminal editor) or using your mouse and allows live collaboration with your buddies all sharing the same virtual keyboard. Most importantly, however, tmux provides a safe way to leave something running and reattach to it later, even if your connection is dropped or your terminal crashes. This is virtually impossible without tmux. Learn it.

[NOTE]
====
I've worked more than 30 years as a remote employee, logging into central enterprise systems responsible for running things that keep products, money, and power flowing. What would happen if during an important, long-running thing my Internet connection died? That exact thing has happened multiple times, but every single time I was able to recover by simply reconnecting to my work network and reattaching tmux (or screen, tmux's ancestor), sometimes while other team members were also connected simultaneously. People who say, "you don't need tmux" are really limiting themselves at best, and living dangerously at worst. A terminal app could crash and you could lose all your work without it.
====

=== Source control: git + gh

Source control systems like Git help manage the spellbooks of developers. They preserve your progress, allow experimentation without fear, and let you collaborate with others seamlessly. GitHub is the leading source control service and uniquely allows repos, pull requests, issues, comments to be managed with the `gh` command line tool (written in Go, btw).

=== Research: w3m + mods + claude

Harnessing the power of command-line tools like the terminal web browser `w3m` and the command line AI query tool `mods` from Charmbracelet powered by the Claude API, creates a streamlined environment for efficient web browsing and AI-assisted research from the terminal that dominates those doing the alternative from graphic user interfaces. This setup ensures you stay focused, efficient, and immersed in the terminal-first environment.

=== Reference: man, help, cm

Unix manual pages can be pulled up with the `man` command. The `help` command contains everything about the `bash` shell. And the Code-Mage `cm` command is there to check your work and provide a local copy of this book anywhere, Internet or not.
