== Launch Alacritty terminal

If you haven't closed out of your native terminal that we used for the initial install steps do so now.

For the rest of rest of this book we will be using Alacritty GPU-accelerated terminal. Launching it is simple now that you know how to launch anything. Mac, Windows, and Linux all use the same application name: `alacritty`.

[CAUTION]
====
Once you have launched `alacritty`, make sure you have a bash shell running. On Windows you will likely need to type `bash + Enter`.
====

Take a moment to figure out how you want to find and launch Alacritty later. Perhaps you want to pin it to your task bar or make a shortcut on the desktop. You decide. You can always launch it the way you did in this step, which is also usually the fastest way. The rest of this book assumes you know how.

[CAUTION]
====
Fight the urge to customize Alacritty too much right now. Perhaps just focus on getting the font to a size that you can read. The `cm init` command will configure Alacritty enough to get going for this book, including making `bash` the default shell for Windows. Later you can come back and change things the way you want. Alacritty configuration is covered in depth in the book https://rwxrob.github.com/books/terminal-velocity[_Terminal Velocity_].
====
