[[learnvim]]
== Learn vim

It's time to learn the world's most powerful terminal editor: Vim. To date, the best way to learn it remains using the very old and broken `vimtutor` program.

[CAUTION]
====
Don't do things like VimAdventures. You won't remember them. The best way to learn Vim is to use `vim`. Finish the `vimtutor` and then start taking notes with your new editing skills. It will be a much better use of your time.
====

[NOTE]
====
I am frantically working on a replacement to `vimtutor` called `learnvim` that will contain all the corrections.
====

Before you begin, make sure you have the list of corrections from my https://rwxrob.github.io/books/learn-vim-well[_Learn Vim Well_] book available to see what is wrong and why.

[source, sh]
----
vimtutor
----

Now, save by writing it to another location:

[source, vim]
----
:w /tmp/vimtutorial
----

Exit so that you can reopen the saved copy:

[source, vim]
----
:ZZ
----

[CAUTION]
====
The `vimtutor` is really stupid about remembering the last file you were editing.
====

Now we can open a file we control:

[source, shell]
----
vi /tmp/vimtutorial
----

[NOTE]
====
Remember that `vi` will actually progressively enhance your editing by searching for `nvim` or `vim` and using that instead if it is there. If not, on AIX Unix, for example, it just works because `vi` is the name of the editor there.
====

After you finish it once, proceed to the next section were we talk about taking notes so you can begin crafting your book of code spells and notes to get the best practice of all.
