== Setup Neovim editor

We've been looking at a lot of text files. Now its time to learn how to edit them in the terminal with the most legendary tool in the code mage's arsenal: Vim and Neovim. These are more than text editors known for their efficiency, power, and adaptability. They transcend the mundane, offering a modal editing experience that lets you manipulate text with precision and speed. While Vim has a long history of being the go-to editor for terminal wizards, Neovim builds on this legacy with modern enhancements, including better extensibility, asynchronous plugins, and a thriving community. Whether you’re crafting code or shaping prose, mastering Vim or Neovim is like learning the incantations of powerful magic, opening the door to unparalleled productivity.

=== Change back into dotfiles directory

Because you started a new terminal you should be back at home on the command line, not figuratively, in your `~` directory (`/home/you` for example). This means you need to change back into your `dot` files directory:

[source, sh]
----
cd dot
----

=== You got this

Everything else is stuff you already know from before. Thanks to the power of the command line, the steps to install and configure Neovim are essentially the same as for bashrc and WezTerm even though they are totally different tools.

Use the new shell commands you just learned (`ls`, `cd`, `man`, `less`, `pwd`) to checkout the `neovim` directory with its configuration files and scripts. When you are ready, install and setup the new `nvim` command by doing the following commands one after another:

[source, shell]
----
./install/neovim
cd neovim
./setup
cd -
----

Notice that we did `cd -` instead of `cd ..` which is a good habit to get into because it changes back to whatever the previous directory was (instead of the parent, which is the same in this case).

=== Confirm installation

Just check the version for now:

[source, shell]
----
nvim --version
----

=== Or is it ...

Try another one:

[source, shell]
----
vim --version
----

Quite a bit different, right?

This is because `vim` was already on the system with Git Bash or the operating system itself. Why install another one you ask?

Neovim is a new (hence `neo`) version of `vim` that addresses several of the original inadequacies of `vim`. In fact, `vim` itself did the same by iMproving `vi`, the original "visual" mode of `ex` a modern version of `ed`, the first computer text editor ever made for—you guessed it—Unix, one of the first computer operating systems ever made.

Whew. That's a lot of history. No other editor can claim that line of authority. You might not care now, but you will when you are on a computer that doesn't have `nvim` or even `vim` in the future. There are hundreds of thousands of them running the world, a world to which you will soon be granted access due to your emerging mage powers.

=== See what I did there?

Try this for fun:

[source, shell]
----
vi --version
----

Notice that it is the same `--version` output as `nvim`. That's because `vi` is an _alias_ for `nvim`. Aliases are expanded by the shell to be something else, could be one word or several. In this case the new `~/.bashrc` you installed is _progressively enhancing_ your editor by detecting what is available and using that. When you ran `neovim/setup` you actually created a `~/.vimrc` file as well as a `~/.config/nvim/init.lua` file even though `nvim` was not yet available. The `.vimrc` file can be put on any system with `vim` or `nvim` on it and it will work. In fact, `nvim` won't even read `~/.vimrc` at that location unless you tell it to (for reasons I don't fully agree with). Instead, `nvim` reads `~/.config/nvim/init.lua` and that reads `~/.vimrc` meaning `~/.vimrc` gets used by _both_ `vim` and `nvim`. Get it? This is the way.

[TIP]
====
This flexibility—at the cost of being able to use super-cool Neovim Lua for all configuration—is critical to a code mage who wants to be productive on any computer in the world. Tens of thousands of computers _already_ have `vim` on them. None already have `nvim`, and, I hate to disappoint you, but you won't usually have permission to install `nvim` on most of them even though you will _always_ have permission to bring your own `.vimrc` file with you.
====

=== Activate your plugins

Neovim and vim have some great plugins. There are entire https://neovimconf.live[NeovimConfs] dedicated just to talking about them. That's how big a deal Vim and Neovim are in the land of tech arcana. For now, however, we only want to get our stuff ready for coding. Let's install and activate out plugins:

[source, sh]
----
vi +PlugInstall +qa
----

This command usually returns rather quickly if you have a good Internet connection. If you want, you can also pull down all the Go binaries that will be needed for Go coding later (or you can wait, I'll remind you):

[source, sh]
----
vi +GoInstallBinaries +qa
----

This one takes significantly longer probably because it is compiling them on the fly while installing them.
