== Setup WezTerm terminal

You've already been using a terminal, but now let's get _the_ terminal. WezTerm is the most amazing terminal I have ever used (and I have used them all over 25 years). You won't understand the full power of WezTerm now, but you will. Just know it is the fastest terminal on the planet, which matters whether it be lag while typing and waiting for hints to appear or just to do fun terminal animations. It's got full support for emojis, italics, and millions of colors unlike other terminals. Plus it's incredibly easy to adapt and configure and fully supported by an amazing team of volunteers who seem like nice people. There's really nothing like it.

=== Install

Installing WezTerm is in one simple command. Have a look at it with the following:

Take a look inside the script:

[source, sh]
----
less install/wezterm
----

That's the bash script we will be using to install wezterm on whatever operating system you are on (Mac, Windows, or Linux).

Ready to install? Okay then:

[source, sh]
----
./install/wezterm
----

There's gonna be all kinds of exciting stuff happening on your screen now. Welcome to the terminal, mage!

=== Setup

After things settle down check that it all looks okay. We have one more command to setup all the configurations:

[CAUTION]
====
Make sure you `cd` or else you will end up configuring everything and not just WezTerm.
====

[source, sh]
----
cd wezterm
./setup
----

You will see more stuff happening. After it finishes, go back up where you came from with the following command:

[source, sh]
----
cd ..
----

This takes you to the _parent directory_ (`..`). You probably already guessed that `.` means current directory.

=== Start up wezterm

All that's left to do is get rid of this tired old terminal and start up your new one.

Close your current terminal window. You can always get it back with either `bash` (Windows) or `terminal` (Mac) in your launcher like before if needed.

Now open up WezTerm using the same launch technique as before but with `wez` as the word.

You should see your terminal open up with the same bash prompt as you had with the older terminal, except it should look _a lot_ better.

Congratulations! You now have the most powerful terminal on the planet to play with and learn to code in. Can't wait to get coding!
