== Setup Wezterm terminal

You've already been using a terminal, but now let's get _the_ terminal. Wezterm is the most amazing terminal I have ever used. You won't understand all its full power now, but you will. Just know it is the fastest terminal on the planet, which matters whether it be lag while typing and waiting for hints to appear or just to do fun terminal animations. It's got full support for emojis, italics, and millions of colors unlike other terminals. Plus it's incredibly easy to adapt and configure and fully supported by an amazing team of volunteers (who are actually nice people). There's really nothing like it.

When you did the `ls` command you probably saw a directory called `wezterm` and another called `install`. The `wezterm` directory is where your configuration setup lives, in the `wezterm/wezterm.lua` file specifically.

[NOTE]
====
Lua itself is a language that is used for configuration in this case. You might have heard about it from WoW or Roblox.
====

=== Less is more

You'll have plenty of opportunity to edit and play with these files later, for now let's just look at them before we set them up. To look into any text file we can use a thing called a _pager_. It just pages through files of text so we can read it from the terminal. We'll use the `less` pager (a newer version of `more`).

Type the following command into the terminal:

[source,sh]
----
less wezterm/wezterm.lua
----

Press space until you reach the end they type `q` to quit. Do it as many times as you like to get friendly with how the pager works. You will be doing it a lot. Notice that there are no colors when paging, this is because a pager does not know about the type of file, only that it is text.

=== Hey man

While we are at it, let's use the pager again in a different way, from the `man` command to read about the `ls` command. Type the following command and `Enter` to see the manual page about the `ls` command:

[source,sh]
----
man ls
----

Notice all the stuff to read. In comparison, try `man bash` for fun as well, but you might have to page several dozen times.

There are few more important commands to learn than `man`. You'll be using it constantly. You'll add it to your notes a bit later in the next sections.

=== Install

Time to install WezTerm in one simple command. Have a look at it with the following:

[source, sh]
----
ls -l install/wezterm
----

Notice the color and the `x` part of `rwx`. That means not only is it a text file, it's also an _executable_, something that can be executed on the system, or run.

[NOTE]
====
It's at this point that everyone is usually saying, "oooohhh, that's where Rob got the `rwx` from." 'Cuz I'm readable, I write a lot, and—most of all—I make stuff happen. Full perms, mother f*cker.
====

Take a look inside the script:

[source, sh]
----
less install/wezterm
----

That's the bash script we will be using to install wezterm on whatever operating system you are on (Mac, Windows, or Linux).

[NOTE]
====
It's always a good idea to look into any script that you can before running it on your computer—especially one that makes as many substantial changes as these installers do.
====

Ready to install? Okay then:

[source, sh]
----
./install/wezterm
----

There's gonna be all kinds of stuff happening on your screen now. Fonts installing, dependencies being checked, progress bars animating. Welcome to the terminal, mage!

=== Setup

After things settle down check that it all looks okay. We have one more command to setup all the configurations:

[CAUTION]
====
Make sure you `cd` or else you will end up configuring everything and not just WezTerm.
====

[source, sh]
----
cd wezterm
./wezterm
----

You will see more stuff happening. After it finishes, go back up where you came from with the following command:

[source, sh]
----
cd ..
----

This takes you to the _parent directory_ (`..`). You probably already guessed that `.` means current directory.

=== Start up wezterm

All that's left to do is get rid of this tired old terminal and start up your new one.

Close your current terminal window. You can always get it back with either `bash` (Windows) or `terminal` (Mac) in your launcher like before if needed.

Now open up WezTerm using the same launch technique as before but with `wez` as the word.

You should see your terminal open up with the same bash prompt as you had with the older terminal, except it should look a lot better.

Congratulations! You now have the most powerful terminal on the planet to play with and learn to code in.
