== There is no 4th wall

Deadpool and Ferris Bueller were just strimmers.

Breaking the fourth wall has always been a thing, but it is even more of a thing now that livestreaming is the norm. People demand connection to their entertainers now more than ever before. Even though I've never considered myself an entertainer, I suppose I am, just like all the other strimmers. I'm just bad at it.

=== Face on stream

"Eyes connect, face builds."

=== Camera position

I've learned to avoid the uncanny appearance that I am looking at the person's forehead or ear by putting the chat too close the camera. When I look into the camera it is like I am actually talking to the person watching, in a good way. It's better to have the chat far away so there is an intentional break in "gaze" signalling that I'm reading what people are saying off screen.

It also follows that looking at coding screen by dropping my gaze away from the line of site with the camera signals to people that I am working on the code and not paying attention to the chat at the moment so they don't immediately expect a response and think I am just ignoring them.

=== Voice and good audio

This is actually something I got right from the beginning. I always said, that I just wanted a radio show that happened to have a video element. I've even read that YouTube is actually primarily an audio service with video as an extra.

=== Forget the green screen

Big strimmers don't use a green screen. In fact, on some of their streams you can see a dead green screen crumpled up in the background. I've learned that people want to see something about my surroundings more than they want to zoom in on just me and whatever I'm wearing. The comments from people were hilarious once I dropped the green screen about what everyone imagined my studio space actually looked like. Some imagined a corporate office, a school classroom, but few expected me to be in my crappy apartment room. The impression came because I used to dress up for streaming (instead of just wearing pajamas) and took it way too seriously. I was such a bad strimmer. The best strimmers are just themselves and everything that makes them human makes them worth watching. Some will pretend and do fine for a while, but the biggest strimmers are themselves.

Sounds like relationship advice, right? Because it is. It's building a relationship with my community.
