== Don't read the comments

"Why are you reading the comments? Just ignore them."

"Oh, I don't know, because it is an opportunity to connect with the people that participate in my community and have things to share, questions, and good ideas."

Silly me. What was I thinking? The best strimmers don't care at all about the people who post comments or even chat messages. It's all about whatever else it could be about (okay, I still haven't figured that part out).

I cannot help but read the comments because that is where people have a chance to give valuable feedback and I can legitimately help them. One of my favorite Gen X streamers, Mat Ryder, always answers all his emails and comments. He even profoundly apologizes when he doesn't get to them all. He has a unique connection with his community that really seems amazing compared to the rest.

=== Okay, maybe read them, but don't _care_ about them

Reading comments and responding build _engagement_, a fancy word that good strimmers don't actually care about explicitly, or at least they don't want people to _know_ they do.

I'm been accused of having too much empathy and that allows trolls to have their way with me. Probably true. If I was a good strimmer I'd make sure to just ignore or delete the bad ones and focus on the positive without letting the haters get to me. But I can't. I'm me. I care about what the random trolls say. I'm a bad strimmer.
