== Stupid titles FTW!

🟥 TITLES AND CATEGORIES 🟥

Some of the biggest hate I've ever got came from having the wrong title or category.

=== The more confusing the better

When I started streaming I really tried hard to have the best possible title and category and to always stay on topic. I would stop and start streams to make sure the titles were correct. But, being me, I would be easily distracted and want to respond to people in my chat—a cardinal sin of streaming, responding to people in chat.

I even created an entire system for managing the title only to realize no matter what I did the final title would always be wrong unless I stopped and restarted the stream every time I randomly changed what I was talking about. It was exhausting, but worse than that, I _still_ got hate.

All it takes is once to have the wrong title on a VOD and people think that I'm the lazy one for not laboriously editing the video into different segments or even changing the title of the VOD or adding a full description of everything in the video. People always seem to have all the solutions figured out and feel strongly that they need to tell me what to do even though they have never produced any content at all. Obviously, I owe then the best possible content I can make, and they deserve it for free (yes, they still complain about ads).

Even when people recommend my VOD to someone in Discord because it covers something interesting that someone else in the forum might want to look into I _still_ get hate and "recommendations" about how to be a better strimmer. These people have no idea how much effort it takes to stream _at all_ and frankly they don't care.

So what's the solution?

_**Make absolutely sure that the titles and categories have absolutely, positively nothing to do with the content of the stream whatsoever.**_

People get justifiably angry when they open up a VOD that says "Come learn to code with us" but contains no coding whatsoever. But if the title is "

Their titles. Look at the biggest streamers in history. Here's an actual title fro Kai Cenat on Thanksgiving day that made sense, sort of:

🦃 MAFIATHON 2 🦃 KAI X KEVIN HART X DRUSKI 🦃DAY 27🦃20% OF REVENUE GOING TO SCHOOL IN NIGERIA 🦃 ALL MONTH 🦃 CLICK HERE 🦃 !Subathon

That's all there is. Most of the time there isn't even that much information, just some random thing that has nothing to do with what is in the stream, at all.

My old gen x mind has a hard time with all this idiocracy but that's where we are. If you want to keep down the hate and keep attracting anyone and everyone long enough to maybe stick around and learn something, make absolutely sure that everyone has no fucking idea what you are doing from the title and category, the worse the better. I mean, we are talking about a generation that thinks setting the reason for a Venmo to "Doink Reattachment Surgery" is actually funny (that's an actual thing that the absolutely unfunny Andy Samburg sent to the dude from A Closer Look).

=== NOT ENOUGH RED

Or should I say 🟥 NOT 🟥 ENOUGH 🟥 RED 🟥 (okay, I could not _stand_ that in my table of contents, the forced caps is bad enough). Silly me. I didn't have enough annoying red emojis in my title. How could I possibly hope to succeed? All the best and biggest strimmers suddenly had an ungodly amount of red emojis. It's as if all these people didn't live through the `<blink>` tag era, and let's face it, they didn't. Hell, they would probably think it was amazing.

=== Lazy wins

It took me four years of streaming to finally realize that I was working _way_ too hard. Why go though all the mental stress of making sure something as trivial as the title and category are accurate when you can just make it the same thing and never change it, or just change it on Thanksgiving to have a bunch of turkeys in it instead.

=== You can always change it later?

Occasionally, someone will say that they found me from one or my long-form, live stream VODs because of the title. That leads me to believe that having a good title _can_ actually help if you make sure you get right. But the only way to make sure it is right is to wait until it is completely over and _then_ decide what to name it. To be safe and lazy just have it make no sense at all, then, after the fact, go change the title and description on YouTube so that people will find it (Twitch VODs don't matter).
