== Unix with Windows

- Git Bash
- MSYS2
- Cygwin
- WSL1
- WSL2
- Podman
- VirtualBox
- VMWare
- Dual boot

=== Git Bash

Git Bash is actually a very slimmed down version of MSYS2 designed to be the most integrated with Windows so that the `git` and other most useful commands associated with Unix appear to be a part of windows.

==== It's just bash on Windows

Perhaps the single biggest reason to use Git Bash is that all the paths are immediately visible. This means that essential tools like `winget` are immediately available without tweaking the `PATH`. It also means that the starting directory is the rather messy default home directory for the user `/c/Users/you`. It might be messy, but it also contains `Downloads` and other directories that make creating scripts to automate the personal things you do on the computer that much nicer. You will see that this is not possible without a lot of work for the options described later.

Git Bash is one of the options that includes direct Windows integration. It _is_ Windows, therefore anything you would do from a windows command line can also be done from Git Bash such as opening of web browsers, video viewers, and other applications. This is extremely powerful when combined with things that require a windows configuration. For example, a tight OBS integration with an application that is tied to Twitch or YouTube for livestreaming. Without this direct integration triggering some behaviors in OBS simply isn't possible. Since OBS is looking at the same file system as Git Bash creating new scenes and resources dynamically is possible. This is not possible with other Unix with Windows options that do not have this integration.
