= What is a SysDE?

A SysDE is a _Systems Developer Engineer_ or _Systems Dev Engineer_, a title that appears to have started at Amazon and is not to be confused with _Systems Engineer_ or _Software Development Engineer_.

> From what I can tell, he didn’t have to go through the entire leetCode monkey dance. What does this position entail on a day to day basis?

> I was convinced that the team would benefit in hiring engineers that are SysDE’s over SDE’s or SE’s.

Looks like the industry has finally footnote:[Okay, 2021 is when articles started popping up even though I didn't see them until 2025. Of course, haven't been looking for a job really in that time.] booted the horrendous SRE (Site Reliability Engineer) title that Google horribly forced on the industry with that horrible book and came up with a reliable replacement that actually covers _exactly_ what I do—and have always done. Once again, Amazon beats Google. The first searches on the Web pull up hits coming from job postings to Amazon, a company that makes heavy use of the title in their job postings. I finally have a title I can reliably search for that is the _exact_ job I want. And guess what, most of these jobs average 200K. I'll be using this title as the primary target for my new _Just Start Your SysDE Career with Go_.

[NOTE]
====
Full disclosure, Amazon is the only company in Silicon Valley that I ever considered seriously joining. I had a great recruiter reach out to me directly and we had a great phone interview, long ago.
====

I prefer the Amazon engineer's ideas on the title over all the academics flailing to figure out what it means. The head of a college I once met with had no idea what Go even was in 2022. Academics regularly have no idea about what the industry is doing, so asking the "dean of [your] college" about industry terms is about as valuable as asking the lunch lady about for loops.

- "application modernization"
- "enterprise development"
- "delivering scalable tooling and automation"
- "expert generalist"

== Traits

According to Ramesh, an Amazon Senior Tech Lead responsible for putting together engineering teams, here are the five main traits describing a SysDE:

. "Technology generalist"
. "Enabling builders"
. "Building systems to scale"
. "Can write software"
. "Great at troubleshooting"

Just reading that list fills me with glee. Finally, I feel seen! I have been doing exactly these things for 30 years and always felt uncomfortable with the titles that didn't quite fit:

- Sysadmins don't do the level of coding that I always have
- SREs are focused on monitoring and uptime of a site
- DevOps is, well, no one really knows
- Infrastructure Engineer is way too broad, but it is generalist
- Software Engineer is horrible, software developers are _not_ engineers
- Software Developer is just someone who imagines and writes code
- Hacker is the closest but it is security related and not about helping devs

== My history

I've been renamed so many titles in my career it's insane—usually while doing exactly the same thing. When I got an 18K raise (if you include bonuses) they changed my title from _Infrastructure Engineer_ to _Senior Backend Systems Software Developer_ even though no one calls me that. At another employer I changed from _IT Specialist_ to _Software Engineer_ and got a $5000 raise (although now I realize just how much they low-balled me there).

Let me highlight the stuff I've worked on over the years, each thing is perfectly in the list of what a SysDE would be focused on doing:

- Middleware API for enterprise applications to submit massive ML jobs
- Monolith utility to replace collection of shell scripts for K8SAPP deployments
- Enterprise deployment of Harbor containing 35 terabytes of container images
- Communication protocol between agents and servers for compliance data
- Data store in PostgreSQL to contain compliance data gathered from agent
- Fork bomb in C to test throttling software
- CGI libraries used by 1000s of users at an ISP
- WebSpinner to allow 1000s of users to create own web pages
- Script to spin up Apache Virtual Server in one command enabling sales people
- Automated build and deployment of `klogin` tool for Kubernetes users
- Exchange rate web page fed from financial source

The point is that these titles don't seem to matter much—until they do. Not getting your title right on a resume or interview or even phone call with someone interested in you can automatically shut doors that lazy interviewers are too lazy to open to figure out what it is you really do.

== Programming

All the Amazon job postings require mastery of "at least one modern programming language" which they list as the following:

* Python
* Ruby
* C/C++
* Golang
* Java
* Rust

A few of the postings did not include Rust or Java. None of them include Perl. All of they have Python and Go prominently listed, probably because all the modern automation and cloud-native tools are written in one of these two languages.

=== Scripting

Perl, Python, Ruby, Bash, POSIX Shell, JavaScript, hell, even TCL for `expect`. A kick-ass SysDE can script in anything—on a Unix system.

A SysDE knows how to read and write any scripting language that exists. They might not be a specialist, and will forget a lot over time, but they can interpret anything that they might encounter or have to integrate.

== Lives for text processing

> Write programs to handle text streams, because that is a universal interface.

SysDEs live for processing text since text is the language of integration and automation—because that is the Unix way. Since Perl is the undisputed leader in text processing—the reason it was created—it remains a dominant skill for all SysDEs. Parsing the same thing in Python or Ruby or Go is often painfully annoying when a SysDE is throwing together a proof-of-concept automation. A SysDE knows why using `awk` is just idiotic compared to `perl` and can articulate why.

== References

- Understanding the Systems Dev Engineer Role +
  <https://www.linkedin.com/pulse/understanding-systems-dev-engineer-role-ramesh-krishnaram>
- Reddit - Dive into anything +
  https://www.reddit.com/r/aws/comments/kk1il5/what_is_a_system_development_engineer_at_aws/
- What exactly is a SysDE? +
  <https://www.reddit.com/r/uwaterloo/comments/85d7tl/what_exactly_is_syde/>
- Unix philosophy - Wikipedia +
  <https://en.wikipedia.org/wiki/Unix_philosophy>
