== What's included in the book

This book is focused on learning to code in Go from the terminal command line and everything that requires for an absolute beginner who has never even heard of a terminal before, that's it, nothing more. It is very rewarding creating command-line programs from the command-line itself. We want to get doing that as fast as possible, but some stuff cannot be skipped to get there. Anything that can, has been.

=== Book organization

This book is divided into four main parts:

. **Understand**: Know what coding and computer science are
. **Prepare**: Get everything ready and master coding prerequisites
. **Learn**: Code memorable micro-projects based on concepts
. **Create**: Develop something useful that you want

[[cm-summary]]
=== Code-Mage Assistant

Code-Mage Assistant was created to skip a lot of that setup stuff with one `cm init` command in a way that you can come back to later and understand it if you want. The source code is available for public review and contribution at the following URL:

https://github.com/rwxrob/code-mage
