== What's included in the book

This book is about learning to code in Go from the terminal. First we have to understand what coding even is. Then we setup a terminal, install a magical text editor and Go for coding, and a find a place to save work so we don't lose it and can share it with others, even have them help write it. After that, the book becomes all about coding on small, silly stuff so you remember it later when you need it. This is the spells thing. Later we'll do some fancier stuff (without the magic metaphors) to help you come up with your own projects to work on that you can show off later.

=== What's with the magic stuff?

The whole fantasy magic theme is fun, right? I hope you like it. It you don't that's fine. No judgement. It's actually for a very good reason: to fool your brain into remembering it even when your brain doesn't want to (the same way people memorize the number Pi to 100,000 digits, Google it). The fact is everything in this book is very real and might even get you a job someday. _Winks at mom._

=== Part of a complete CS breakfast

This book is just one part of a complete Computer Science education breakfast. If you truly want to deeply understand programming, with a full comparative examination of different paradigms, languages, and in-depth computer science concepts, then something like Harvard's free CS50 might be a better first introduction. This book covers just enough of that stuff to generally understand it but focuses more on one specific language to produce actual, usable software. The main difference between these approaches is what you _get_. With CS50 you get understanding, which is important. With this book you get one or two apps you can showcase to demonstrate your employable skills.
