== Who should read this book

This book was written for _**12-year-olds who want to learn to code like a hacker in the terminal**_. I've found that twelve is the ideal age to learn to code for most: math and typing skills are good, cognitive abilities sound, and—hormones haven't _completely_ taken over their brains.

[NOTE]
====
I personally started coding when I was around 13 years old, mostly because there were no computers available until then. In 1979 the Atari 400 came out and my Junior High had exactly one of them sequestered away in a back room of the library where Mr. Bevans, the media coordinator, was the only one allowed to use it—until I came along. I suppose he took pity on my for all the bullying I got. Whatever the reason, I was the _only_ kid in the entire school who got to use that computer. Every morning I took refuge in front of the dark glow of this magical box in front of me. I was _completely_ hooked. The power!

In true 80s nerd fashion my first program was in BASIC loaded into a cartridge with its own paper manual. I've always coded something I _wanted_, never coding for coding sake. I have too many other things I want to do. I _wanted_ a Dungeons and Dragons character stats generator to save me from hours of dice rolling. We'll code one later in the book. It's a surprisingly fun program to write.

I did play a _lot_ of Dungeons and Dragons when I was 11. I think our human brains are just ready for the challenge around that age, some earlier, some later. I even overcame my nerdy shyness to approach the only person in my Junior High who played regularly. We stayed friends all through school serving in High School executive council together. He's a rich surgeon now and occasionally takes me out on Lake Powell on his fancy house boat. Love that dude. Nothing like a rich, caring nerd for a friend.

It was all the complexity and fantasy that drew me in to D&D, computers were just a tool to make _that_ even more fun. I would pour over those pages studying every single fact. My brain was starving for a challenge. Maybe you are having that same feeling reading these pages. I certainly hope so, that's what I'm going for,  _The Player's Handbook of Code_. (Humm, maybe I should reconsider the title.)
====

=== Wait, what are _you_ doing here?

I see you! You are _definitely_ not twelve years old. That's okay. I've helped bar tenders, homemakers,  even grandparents learn to code in the same silly way.

Some of you probably already know how to code. If that describes you, have a look at the following URL where you can setup everything in the book in a `podman` container:

  https://github.com/rwxrob/code-mage

The container has a few limitations since the version of Neovim is so old, but other than that, it's the same as doing all the steps of the <<prepare, Prepare section>> for you.

=== Dear parents and pedagogues

[NOTE]
====
Hey kids, skip this long, boring section. The grown ups are talking.
====

Some of you are parents and pedagogues. Let me talk to you for a second.

First of all, thank you for being _awesome_! It takes a lot to bring kids into this world and even more to dedicate your life to helping kids that aren't even your own to find their way and learn something even if they don't want to. Deep respect.

If you are like me you are wondering, "who the heck is this guy and should I trust those in my care to his wild ramblings?" In so many ways you really shouldn't, I'm a degenerate in the first degree, but when it come to helping kids learn to code, well, that's my super power. I don't mess around—I mean—I do mess around but, um—you know what I mean.

While it is true that this book can be thought of as a text book for absolute beginners with enough algebra to understand what a mathematical function is, the book is very clearly written to include everyone _outside_ of educational institutions. In fact, I wrote it mostly with pro-active _parents_ in mind who want to give their kids a head-start in tech (not teachers). I was a scout master for more than a decade and the scouts and their parents constantly asked me, "Mr. Rob, teach us to code. Teach us to hack, Mr. Rob."

So yes, this _could_ be a "text book" but quite honestly, I _hate_ text books. Too stuffy, too full of themselves, to overpriced and written for the adult members of the board of education who are going to cut the check (do they still have checks?) Really though, who is thinking of the children, yes, _the children_ the ones for whom we are doing this, right? (Not even a dangling preposition, my God I'm good.) I could name names, but I won't. You pompous, bombastic, airbags know who you are and I _never_ want to be grouped with you, ever.

To be completely honest, it is virtually impossible to find this sort of thing in most traditional education systems. AP Computer Science? Please. They still teach that Java single class inheritance is a _good_ thing.

In fact, I started SKILSTAK Coding Arts in 2013 with my own retirement money to address the _real_ needs of the coding industry and those who might consider it as a career, the next generation of coding super-heroes. Hundreds of launched heroes later and here I am writing all this down for the next thousand or more.

Still skeptical? What if I told you that I really have helped a lot of people get started in tech, like a _lot_. One of them quit his grocery clerk job to write code for a solar energy company and had his own intern at 16. Another couldn't get a job with a psychology degree so he learned this stuff and got a starting salary over $100,000. Another drove 40 minutes both ways just to attend our sessions for _four years_ and went on to create an entire coding club at her rural school. I keep a _nice things_ file full of real comments from people like these that keeps me going even when the money doesn't (which is the reason I still have a full-time job and it ain't writing books, although it probably should have been).

The point is, these stories don't have to be about someone else. They can be about someone you know and care about. Coding really does change lives and I'm here to help in whatever way I can.
