== Who should read this book

This book is written for anyone wanting to learn—or help someone learn—practical computer science and programming for real applications development and come away with a project or two that proves you can be trusted for your programming skills. While we have fun with the whole fantasy magic theme, everything in this book is very real and might even get you a job someday. It is true that this book can be reliably used as a text book for absolute beginners with enough algebra to understand what a mathematical function is but this book very clearly includes everyone _outside_ of educational institutions. In fact, I wrote it mostly with pro-active parents in mind who want to give their kids a head-start in tech that they simply cannot find in most traditional education systems, the same reason, in fact, that I started SKILSTAK Coding Arts in 2013 with my own retirement money.

[NOTE]
====
This book is but one part of a more complete Computer Science education breakfast. If you truly want a handle on what "programming" means and a comparative examination of different of paradigms, languages, and in-depth computer science concepts then something like Harvard's free CS50 might be a better first introduction. This book covers just enough of that to understand it generally but focuses deeply on one specific language to produce actual, usable software by the end. The main difference between these approaches is what you _get_ at the end. With CS50 you get understanding, which is important. With this book you get one or two apps you can showcase to demonstrate your employable skills. You decide which is best for you based on your goals.
====
