== Who should read this book

Please don't take this the wrong way: this book was written for 12-year-olds, the type who want to learn to code like a hacker in the terminal. But if that isn't you, you still could learn something. Bar tenders, homemakers,  grandparents. I've helped them all in the same silly way.

== Dear parents and pedagogues

Here, let me just talk to the parents and pedagogues for a second. It'll be easier. Skip this part if it bores you. It's all good. It's okay if you are wondering who the heck this guy thinks he is. I know I would be.

While it is true that this book can be thought of as a text book for absolute beginners with enough algebra to understand what a mathematical function is, the book is very clearly written to include everyone _outside_ of educational institutions. In fact, I wrote it mostly with pro-active _parents_ in mind who want to give their kids a head-start in tech (not teachers). I know that might come as a surprise to those who have gotten used to overpriced books written with the intent of impressing the board of education more than actually helping the reader learn anything.

To be completely honest, it is virtually impossible to find this sort of thing in most traditional education systems. AP Computer Science? Please. They still teach that Java inheritance is a _good_ thing.

In fact, I started SKILSTAK Coding Arts in 2013 with my own retirement money to address the _real_ needs of the coding industry and those who might consider it as a career, the next generation of coding super-heroes. Hundreds of launched heroes later and here I am writing all this down for the next thousand or more.

Still skeptical? What if I told you that I really have helped a lot of people get started in tech, like a _lot_. One of them quit his grocery clerk job to write code for a solar energy company and had his own intern at 16. Another couldn't get a job with a psychology degree so he learned this stuff and got a starting salary over $100,000. Another drove 40 minutes both ways just to attend our sessions for _four years_ and went on to create an entire coding club at her rural school. I keep a _nice things_ file full of real comments from people like these that keeps me going even when the money doesn't (which is the reason I still have a full-time job and it ain't writing books, although it probably should have been).

The point is, these stories don't have to be about someone else. They can be about _you_ or someone you know and care about. Coding really does change lives and I'm here to help.
