= Appendix: Behind the curtain

Welcome to "Behind the curtain," where we reveal the intricate mechanics powering the magic powering Code-Mage spells like `cm init` and `cm work`. This section is for the curious, the builders, and those who want to understand and take control of their tools. Here, you'll learn how to set up everything manually, step by step. While this might seem like "the hard way," it’s also the most illuminating. It comes at the back of the book because really you shouldn't worry about this stuff until you have at least gained some mastery of coding. Whether you’re here out of curiosity or necessity, this journey will deepen your understanding of the magic that makes it all possible.

[NOTE]
====
These sections were once part of the main Prepare section of the book and have since been replaced with <<install-pde, Install PDE>>. This is why they still read like they are positioned there in the book. I decided to preserve them here after `cm init` was created to save time.
====

include::go.adoc[]

include::cm.adoc[]

include::bash.adoc[]

include::alacritty.adoc[]

include::gh.adoc[]

include::git.adoc[]

include::tmux.adoc[]

include::neovim.adoc[]
