== Install terminal

We'll be doing everything from the terminal or more specifically, the _terminal user interface_ (TUI). You might have terminals before, probably in a movie with hackers. They look rather retro, but they are still very much in use today. On the surface, a terminal just looks a bunch of glowing text and a pulsating prompt waiting for you to type in your magical commands. Just using the terminal is a form of coding magic where each command line is an actual line of code.

Terminals are powered by an interactive programming language called a _shell_. The shell gets its name because it surrounds the complicated insides of a computer operating system. Before there were graphics user interfaces (GUI) the shell was the only way to tell the computer what to do, by typing in one command at a time on the command line. This type of interface with a prompt and entering one command at a time is called the _command line interface_ (CLI). A CLI requires a TUI and is the simplest human-computer interface possible.

Just as there are many different programming languages there are many different shell since a shell is literally a programming language. In fact, you can put several commands into a file (a script) and run them all sequentially by running the file itself as a command. Programming shells like this is often called _scripting_ since there is nothing to build or compile.

=== The bash shell

The most beginner-friendly and common shell is the Bourne Again Shell `bash`. It runs on all computer operating systems.

[NOTE]
====
The book https://rwxrob.github.io/books/terminal-velocity[*Terminal Velocity*] talks more about shells and how to get good with scripting in bash.
====

=== On Windows, install Git Bash

Windows comes with the `powershell` shell built in. While powerful, it is not beginner-friendly at all so we to install bash. The simplest and fastest way to get bash installed is to install it along with another powerful tool: git. We'll learn more about git later. For now, just know that they come together. Here's how to install Git Bash:

Start a terminal by pressing `Win` key and entering `powershell`. This will open a terminal. Now type the following `winget` command to install Git Bash:

[source,shell]
----
winget install --id git.git
----

Wait for the output and check it to be sure everything worked. Then close the `powershell` terminal and open a `bash` terminal instead by pressing `Win` key and entering `bash`. You should see a terminal open up. Resize it if you want, but don't spend too much time customizing it because we'll be installing another terminal program later. You are now ready to continue.

=== Open terminal on Mac and Linux

There's no need to do any early installation of bash on Mac or Linux since it is already there. Only a terminal is needed.

On Mac, type `Command + Space` to open Spotlight and enter the word `terminal`. You should see a terminal open up. Even though this shell is `zsh` it will still work to run the installer.

On Linux `Control + Alt + T` works on most systems. The default shell on most Linux systems is already `bash`.

=== Run the remote installer script

For the sake of time, we are going to run an installer script that we download off the Internet from a trusted site using a program called `curl`. This command installs several programs and makes many changes to the current computer user configuration.

[WARNING]
====
Be absolutely sure you are authorized to make any changes to your computer and that you have administrator permissions to do that. If you have any doubt about that, be sure before you proceed.
====

Cut and paste or type out the following command exactly in your open bash terminal window:

[source,shell]
----
bash -c $(curl -fsSL https://rwxrob.github.io/code-mage/install)
----

This will do a whole lot of stuff so monitor it and answer the prompts when they pop up. If for some reason anything goes wrong, you can always try it again after fixing whatever is needed.

Congratulations! You now have everything you need to start coding from the terminal.
