== Install terminal tools

We'll be doing everything from the terminal or more specifically, the _terminal user interface_ (TUI). You might have terminals before, probably in a movie with hackers. They look rather retro, but they are still very much in use today. On the surface, a terminal just looks a bunch of glowing text and a pulsating prompt waiting for you to type in your magical commands. Just using the terminal is a form of coding magic where each command line is an actual line of code.

Terminals are powered by an interactive programming language called a _shell_. The shell gets its name because it surrounds the complicated insides of a computer operating system. Before there were graphics user interfaces (GUI) the shell was the only way to tell the computer what to do, by typing in one command at a time on the command line. This type of interface with a prompt and entering one command at a time is called the _command line interface_ (CLI). A CLI requires a TUI and is the simplest human-computer interface possible.

Just as there are many different programming languages there are many different shell since a shell is literally a programming language. In fact, you can put several commands into a file (a script) and run them all sequentially by running the file itself as a command. Programming shells like this is often called _scripting_ since there is nothing to build or compile.

=== The bash shell

The most beginner-friendly and common shell is the Bourne Again Shell `bash`. It runs on all computer operating systems.

[NOTE]
====
The book https://rwxrob.github.io/books/terminal-velocity[*Terminal Velocity*] talks more about shells and how to get good with scripting in bash.
====

=== Open a terminal

On Windows, type `Win` to open Search and enter the word `powershell`. You should see a terminal open up. Even though this shell is not bash it will still work to run the installer.

On Mac, type `Command + Space` to open Spotlight and enter the word `terminal`. You should see a terminal open up. Even though this shell is `zsh` it will still work to run the installer.

On Linux `Control + Alt + T` works on most systems. The default shell on most Linux systems is already `bash`.

=== Run the remote installer script

For the sake of time, we are going to run an installer script that we download off the Internet from a trusted site. These commands installs several programs and make many changes to the current computer user configuration.

[WARNING]
====
Be absolutely sure you are authorized to make any changes to your computer and that you have administrator permissions to do that. If you have any doubt about that, be sure before you proceed.
====

Cut and paste or type out the following command exactly in your open bash terminal window:

Mac, Linux:

[source,shell]
----
bash -c $(curl -fsSL "https://raw.githubusercontent.com/rwxrob/code-mage/HEAD/install.bash")
----

Windows:

[source,powershell]
----
& ([scriptblock]::Create((iwr 'https://raw.githubusercontent.com/rwxrob/code-mage/HEAD/install.ps1')))
----

This will do a whole lot of stuff so monitor it and answer the prompts when they pop up. If for some reason anything goes wrong, you can always try it again after fixing whatever is needed.

Congratulations! You now have everything you need to start coding from the terminal.
