== Redirect user.github.io

Many GitHub users are unaware that creating a special repo that matches your username plus `github.io`, https://rwxrob.github.io, for example. Most use that with a custom domain name to host their main landing page on the Web. But what if you just used your GitHub profile instead? After all, unless you are a designer you really have no reason to showcase your ability to create a custom Web page.

[NOTE]
====
The more significant the person, the less likely they are to have a fancy web page. I always chuckle at https://bford.info[Bryan Ford's web site]. He's the inventor of Parsing Expression Grammars with multiple significant technology and academic credits to his name, but he's completely content to have a 1990s web site. He has nothing to prove with a flashy web template design.
====

Here's the content of `index.html` you can add just such a GitHub repo that simply redirects anyone to your meticulously crafted and always up to date GitHub profile instead. Change `rwxrob` to your own name:

[source,html]
----
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="0; url=https://github.com/rwxrob">
    <title>Redirecting...</title>
</head>
<body>
    <p>If you are not redirected automatically, follow this <a href="https://github.com/rwxrob">link</a>.</p>
</body>
</html>
----
