== CV vs resume

The goals of these two critical documents are radically different, one is to capture everything you have ever done in specific detail, the other is to intrigue someone with just enough enticing highlights of you to make them want to talk to you in an interview and give them something to remind them what to ask you about (alont with the dozens of others they will be interviewing).

=== CV is exhaustive, everything you have ever done

=== Resume it provocatively short

> "Resume is the Tinder pic that gets you the date." (Insanit13s)

==== Resume is _not_ to get you in the door, its to get an interview

One of the biggest failed ideas about resumes is that somehow some system is going to crunch it and magically submit you to another person who is going to be so impressed they are going to cold-call you on the spot. This has *never* happened. Employment opportunities start with a human connection and relationship that leads to initial trust that you can do the job. At that point, the resume is usually a formality that has to be submitted to HR before they can give you the interview. Sometimes organizations will create a job posting just so you can submit the resume even though they have no intention of interviewing anyone else.

==== No keywords, no one cares

